### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by avoinea** [collective/Products.MemcachedManager#6]
Any plans to release 1.1 in the near future?

**Comment by laulaz** [comment]
@hvelarde +1, would it be possible to make a new release ?
Or to give me release rights on pypi (user : laz) ?

Thanks a lot !

**Comment by ale-rt** [comment]
I am assigning this to the people I found here https://pypi.org/project/Products.MemcachedManager/
If you agree I can even be added as a PyPI maintainer (my PyPI account is `alert`).

**Comment by ale-rt** [comment]
CC @wichert @tesdal

**Comment by wichert** [comment]
@ale-rt I've made you an owner on PyPI

**Comment by ale-rt** [comment]
Thanks!

**Comment by ale-rt** [comment]
I released version 1.1 https://pypi.org/project/Products.MemcachedManager/
